// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlTqrmWe3ChFpo-4CL6oTwZ9HYyHzluQ',
    appId: '1:766748188395:web:a7005a2c5fd2ee365a28ae',
    messagingSenderId: '766748188395',
    projectId: 'home-rent-flutter-d86eb',
    authDomain: 'home-rent-flutter-d86eb.firebaseapp.com',
    storageBucket: 'home-rent-flutter-d86eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4OXGnipRpQT5iqU3j-Lyd_B59_lE-wao',
    appId: '1:766748188395:android:a149de0ae3ab6c015a28ae',
    messagingSenderId: '766748188395',
    projectId: 'home-rent-flutter-d86eb',
    storageBucket: 'home-rent-flutter-d86eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdoVB3nM_rELDM_4obKRSFug_MdKO2Eg',
    appId: '1:766748188395:ios:614c17d213e1a6115a28ae',
    messagingSenderId: '766748188395',
    projectId: 'home-rent-flutter-d86eb',
    storageBucket: 'home-rent-flutter-d86eb.firebasestorage.app',
    iosBundleId: 'com.example.homeRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdoVB3nM_rELDM_4obKRSFug_MdKO2Eg',
    appId: '1:766748188395:ios:614c17d213e1a6115a28ae',
    messagingSenderId: '766748188395',
    projectId: 'home-rent-flutter-d86eb',
    storageBucket: 'home-rent-flutter-d86eb.firebasestorage.app',
    iosBundleId: 'com.example.homeRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIlTqrmWe3ChFpo-4CL6oTwZ9HYyHzluQ',
    appId: '1:766748188395:web:aabbd6a5b194befc5a28ae',
    messagingSenderId: '766748188395',
    projectId: 'home-rent-flutter-d86eb',
    authDomain: 'home-rent-flutter-d86eb.firebaseapp.com',
    storageBucket: 'home-rent-flutter-d86eb.firebasestorage.app',
  );
}
